### PR TITLE
Check for mismatched attributes in shapely_geometry_to_vector

### LINKED ISSUE #226: Handle malformed keys in shapely_geom_to_vector
This issue stems from InVEST issue: https://github.com/natcap/invest/issues/545. A bad key was passed in with the attribute list which caused unhelpful `ERROR 1: Invalid index : -1` to appear.

Proposed solution:
Check to make sure the keys in the attribute list match the field name and raise a helpful ValueError if not.

T.E. 1-3 hours

### PR DESCRIPTION
**Pull request by phargogh**
`shapely_geometry_to_vector` will now raise an exception when the provided attributes of a feature don't match the defined fields.

Fixes #226 

This PR is currently in draft while I debug a build issue.

### CODE REVIEW

**Comment by phargogh** [comment]
This PR is pending approval and merging of #231 so that the included `setup.py` command invocations can be included here.

**Review by dcdenu4 — COMMENTED** [review]
Hey @phargogh, I see this is still in draft and is on hold but it looks good to me. I'll take another look and approve when this moves out of draft.

**Comment by phargogh** [comment]
Thanks @dcdenu4 !  I've marked this PR as ready for review and have resolved the merge conflicts that resulted from the other PR so I think this will be ready to go once the tests pass.

**Review by dcdenu4 — APPROVED** [review]
Looks good.

**Pull request merged**
