### PR TITLE
fixes #37 just fixing the log and updating history

### LINKED ISSUE #37: Rasterization progress logging is malformed
When rasterizing a layer in pygeoprocessing, the progress logging is malformed when other progress logging elsewhere in pygeoprocessing works great.  Here's a sample from InVEST 3.8.0 SDR / pygeoprocessing 1.9.2:

```
2020-03-01 13:51:28,374 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9433283763687982, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:51:35,635 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9508449371366771, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:51:46,256 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9621197782884954, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:51:57,458 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9733946194403137, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:52:04,157 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9809111802081925, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:52:14,198 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 0.9921860213600108, message: RasterizeLayer %.1f%% complete %s
2020-03-01 13:52:22,923 geoprocessing.logger_callback(3243) INFO p_progress_arg is None df_complete: 1.0, message: RasterizeLayer %.1f%% complete %s
```

And here's some other logging (not sure which operation is calling it) from the same InVEST model run: 

```
2020-03-01 13:52:28,458 geoprocessing.<lambda>(451) INFO 0.5% complete
2020-03-01 13:52:33,461 geoprocessing.<lambda>(451) INFO 1.0% complete
2020-03-01 13:52:38,462 geoprocessing.<lambda>(451) INFO 1.5% complete
2020-03-01 13:52:43,464 geoprocessing.<lambda>(451) INFO 2.0% complete
2020-03-01 13:52:48,466 geoprocessing.<lambda>(451) INFO 2.5% complete
2020-03-01 13:52:53,468 geoprocessing.<lambda>(451) INFO 3.0% complete
2020-03-01 13:52:58,470 geoprocessing.<lambda>(451) INFO 3.5% complete
2020-03-01 13:53:03,471 geoprocessing.<lambda>(451) INFO 4.0% complete
2020-03-01 13:53:08,472 geoprocessing.<lambda>(451) INFO 4.5% complete
2020-03-01 13:53:13,475 geoprocessing.<lambda>(451) INFO 5.0% complete
2020-03-01 13:53:18,475 geoprocessing.<lambda>(451) INFO 5.4% complete
2020-03-01 13:53:23,477 geoprocessing.<lambda>(451) INFO 5.9% complete
2020-03-01 13:53:28,478 geoprocessing.<lambda>(451) INFO 6.4% complete
2020-03-01 13:53:33,480 geoprocessing.<lambda>(451) INFO 6.9% complete
```

### PR DESCRIPTION
**Pull request by richpsharp**
This was an easy one, looks like I had a special case in `_make_logger_callback` if the `p_progress_arg` parameter was None. I think I'd interpreted that as a bug back in the day and hastily put a log message in there. I've since replaced it with a log that will look like this on a long rasterize (I ran it locally):

```
2020-05-06 00:14:44,633 (7266) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 2.4% complete
2020-05-06 00:14:53,895 (16529) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 3.6% complete
2020-05-06 00:15:03,073 (25707) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 4.8% complete
2020-05-06 00:15:11,705 (34339) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 6.0% complete
2020-05-06 00:15:19,903 (42537) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 7.2% complete
2020-05-06 00:15:28,060 (50694) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 8.5% complete
2020-05-06 00:15:38,641 (61275) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 9.7% complete
2020-05-06 00:15:47,133 (69767) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 10.9% complete
2020-05-06 00:15:55,927 (78560) INFO pygeoprocessing.geoprocessing [logger_callback:3258] RasterizeLayer 12.1% complete
```

I didn't update any tests for this because of the complexity that I can go into if you need.

Closes issue #37

### CODE REVIEW

**Review by phargogh — CHANGES_REQUESTED** [review]
Looks good to me, @richpsharp !  There's just a merge conflict on `HISTORY`.

**Comment by richpsharp** [comment]
Hi @phargogh, I fixed the history merge conflict, since you marked "changes requested" I can't merge though so I re-requested your review.

**Comment by richpsharp** [comment]
Also, if it's a tirival merge conflict in HISTORY, I think that's okay for the reviewer to fix right? Is that possible? (I feel like we talked about this before).

**Review by phargogh — APPROVED** [review]
Ah, yes, I should have marked as approved.  Sorry about that!  We had indeed talked about it before.

**Pull request merged**
